### ISSUE TITLE
question: the `poll-events` didn't call the `mouse-moved` method in `my-window` class.

### ISSUE THREAD

**Issue by sakurawald** [Shirakumo/glfw#12]
What did I do wrong?

![image](https://github.com/user-attachments/assets/8a1b6c01-628b-47df-9d2a-9b64bf423292)

**Comment by Shinmera** [comment]
Package failure. You're not defining a method on the glfw function, but rather a method on another generic function that doesn't exist.

**Comment by sakurawald** [comment]
> Package failure. You're not defining a method on the glfw function, but rather a method on another generic function that doesn't exist.
> […](#)
> On 6 November 2024 13:32:00 CET, sakurawald ***@***.***> wrote: What did I do wrong? ![image](https://github.com/user-attachments/assets/8a1b6c01-628b-47df-9d2a-9b64bf423292) -- Reply to this email directly or view it on GitHub: #12 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

sorry, but what i don't understand is that, here the `my-window` did extends the `org.shirakumo.fraf.glfw:window` class. so why this doesn't work.

**Comment by sakurawald** [comment]
i add the `package prefix` to the `define-method`, now it works!

**Comment by sakurawald** [comment]
I guess it, the `generic function` and the `methods` are not belongs to the `class`, they belongs to the `pacakge`.

**Comment by Shinmera** [comment]
To be precise, methods belong to a generic function, which is named by a symbol, which may be home to a package, and may be interned in several packages.
