### ISSUE TITLE
Quicklisp install leads to error: trivial-deprecate is not found

### ISSUE THREAD

**Issue by Kungi** [Shirakumo/glfw#4]
I tried to install trial-glfw vial quicklisp.
`(ql:quickload :trial-glfw)`

Which leads to the following error:
`System "trivial-deprecate" not found`

Can you please release trivial-deprecate on ultralisp?

**Comment by Shinmera** [comment]
trial-glfw is not glfw. this is the wrong repo.

I'm also not responsible for ultralisp.

**Comment by Shinmera** [comment]
If you want to use Trial, please follow its http://shirakumo.github.io/trial/start.html instructions.
