### ISSUE TITLE
No symbol version section for `memcpy@GLIBC_2.2.5` on linux ARM64

### ISSUE THREAD

**Issue by sorumehta** [Shirakumo/glfw#8]
I am running linux (fedora) on arm64 architecture (apple silicon). When I run `make` inside glfw/lib, after compilation I get the following error during linking step:

> no symbol version section for versioned symbol `memcpy@GLIBC_2.2.5`

I do want to fix this and create a PR, but I am not really sure where to begin.
One thing I noticed that in the directory `glfw/lib/glibcver` there are platform specific files like [glibc_2.9_x64.h](https://github.com/Shirakumo/glfw/blob/main/lib/glibcver/glibc_2.9_x64.h), but no corresponding glibc file for arm64. Can this be one of the causes? 

Thanks.

**Comment by Shinmera** [comment]
Okey, looks like wheybags/glibc_version_header#35 is outstanding for now. I've just disabled static glibc version linking for now on ARM64, which means the produced binary will be tied to the host's GLIBC version number (and thus not be backwards compatible), but at least the compilation should succeed now.

**Comment by sorumehta** [comment]
@Shinmera Thank you! I am able to build it now, and raised a PR. But I am not sure how would the new file be located by cffi? Does it need to have a particular naming pattern?
